server:
    port: 8081
spring:
    application:
        name: guests-service
    datasource:
        password: admin
        url: jdbc:postgresql://localhost:5435/guest
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: true
