spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Wedding
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081