spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: moghoneim
    password: moghoneim
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: user-service

server:
  port: 8081