spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/user
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: user-service

server:
  port: 8082